name: tempfiles_mobile_beta
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.3
  dio: ^5.4.0
  equatable: ^2.0.5
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_animation_progress_bar: ^2.3.1
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  intl: ^0.19.0
  retrofit: ^4.0.3
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^8.0.6
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
